version: "3.9"
services:
  structurizr:
    image: structurizr/onpremises:2024.06.25
    ports:
      - "${HTTP_PORT:-8080}:8080"
    volumes:
      - structurizr_data:/usr/local/structurizr

volumes:
  structurizr_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STRUC_DIR:-~/structurizr}  # remember to create this directory
#  structurizer_data:
#    driver: local
#    driver_opts:
#      type: nfs
#      o: addr=...
#      device: ...